[tools]
bun = "latest"
go = "latest"
java = ["zulu-17", "zulu-21", "zulu-24"]
node = "latest"
yarn = "latest"
rust = "latest"
"cargo:git-trim" = "latest"
usage = "latest"
"npm:@github/copilot" = "latest"
"npm:@biomejs/biome" = "latest"
"npm:opencode-ai" = "latest"
uv = "latest"
"pipx:unrpa" = "latest"
"npm:azure-functions-core-tools" = "4"
"npm:azurite" = "latest"
dotnet = ["10", "9", "8", "7", "6"]
"npm:opencode-wakatime" = "latest"

[settings]
idiomatic_version_file_enable_tools = []
experimental = true
