[tools]
bun = "latest"
deno = "latest"
go = "latest"
java = ["zulu-17", "zulu-24"]
node = "latest"
yarn = "latest"
rust = "latest"
"cargo:git-trim" = "latest"
usage = "latest"
"npm:@github/copilot" = "latest"
"npm:@biomejs/biome" = "latest"
dotnet = ["10", "9", "8"]
"dotnet:PowerShell" = "latest"

[settings]
idiomatic_version_file_enable_tools = []
experimental = true
lockfile = true
