[tools]
bun = "latest"
go = "latest"
node = "latest"
yarn = "latest"
rust = "latest"
usage = "latest"
uv = "latest"
java = ["zulu-17", "zulu-21", "zulu-24"]
"cargo:git-trim" = "latest"
"npm:corepack" = { version = "latest", postinstall = "corepack enable" }
"npm:@biomejs/biome" = "latest"
"npm:azure-functions-core-tools" = "4"
"npm:azurite" = "latest"
"npm:@bufbuild/buf" = "latest"
"pipx:unrpa" = "latest"
"pipx:git+https://github.com/github/spec-kit.git" = "latest"
"npm:@ast-grep/napi" = "latest"
"npm:@electron/asar" = "latest"
"npm:@google/gemini-cli" = "latest"
"npm:@openai/codex" = "latest"

[settings]
idiomatic_version_file_enable_tools = []
experimental = true
