[tools]
bun = "latest"
go = "latest"
java = ["zulu-17", "zulu-24"]
node = "latest"
yarn = "latest"
rust = "latest"
"cargo:git-trim" = "latest"
usage = "latest"
"npm:@github/copilot" = "latest"
"npm:@biomejs/biome" = "latest"
uv = "latest"
"ubi:sst/opencode" = "latest"

[settings]
idiomatic_version_file_enable_tools = []
experimental = true
