[tools]
bun = "latest"
go = "latest"
node = "latest"
yarn = "latest"
rust = "latest"
usage = "latest"
uv = "latest"
java = ["zulu-17", "zulu-21", "zulu-24"]
"cargo:git-trim" = "latest"
"npm:@github/copilot" = "latest"
"npm:@biomejs/biome" = "latest"
"npm:opencode-ai" = "latest"
"pipx:unrpa" = "latest"
"npm:azure-functions-core-tools" = "4"
"npm:azurite" = "latest"
"npm:opencode-wakatime" = { version = "latest", postinstall = "opencode-wakatime --install" }
"npm:@bufbuild/buf" = "latest"

[settings]
idiomatic_version_file_enable_tools = []
experimental = true
