[tools]
bun = "latest"
go = "latest"
node = "latest"
yarn = "latest"
rust = { version = "latest", components = "rust-analyzer,rust-src" }
usage = "latest"
uv = "latest"
java = ["zulu-17", "zulu-21", "zulu-25"]
"cargo:git-trim" = "latest"
"npm:@biomejs/biome" = "latest"
"npm:azure-functions-core-tools" = "4"
"npm:azurite" = "latest"
"npm:@bufbuild/buf" = "latest"
pipx = { version = "latest", os = ["linux", "macos"] }
"pipx:unrpa" = "latest"
"pipx:git+https://github.com/github/spec-kit.git" = "latest"
"npm:@ast-grep/napi" = "latest"
"npm:@electron/asar" = "latest"
"npm:@google/gemini-cli" = "latest"
"npm:@openai/codex" = "latest"
"npm:opencode-ai" = "latest"
"github:rust-lang/rust-analyzer" = "latest"
"npm:typescript-language-server" = "latest"
ruby = [
  { version = "latest" },
  { version = "3.4", os = ["linux", "macos"] },
  { version = "3.2", os = ["linux", "macos"] }
]
"npm:npm" = "latest"
"npm:shadcn" = "latest"
"npm:lucide-icons-mcp" = "latest"
"npm:@tanstack/cli" = "latest"

[settings]
idiomatic_version_file_enable_tools = []
experimental = true

[settings.ruby]
compile = false
